package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;
import edu.wpi.first.wpilibj.motorcontrol.PWMVictorSPX;


public class tanks {

    private PWMVictorSPX left1;
    private PWMVictorSPX left2;
    private MotorControllerGroup leftMotor;
    private PWMVictorSPX right1;
    private PWMVictorSPX right2;
    private MotorControllerGroup rightMotor;
    private DifferentialDrive drive;
    private Encoder leftencoder;
    private Encoder rightencoder;
    private AnalogGyro gyro;
    private AnalogInput rangefinder;


    left1 = new PWMVictorSPX(0);

    public void drivetrain(){
        left1 = new PWMVictorSPX(0);
        //addChild("left1",left1);
        left1.setInverted(false);

        left2 = new PWMVictorSPX(1);
        //addChild("left2",left2);
        left2.setInverted(false);

        leftMotor = new MotorControllerGroup(left1, left2);
        //addChild("leftMotor", leftMotor);

        right1 = new PWMVictorSPX(2);
        //addChild("right1",right1);
        right1.setInverted(false);

        right2 = new PWMVictorSPX(3);
        //addChild("right2",right2);
        right2.setInverted(false);

        rightMotor = new MotorControllerGroup(right1, right2);
        //addChild("rightMotor", rightMotor);


    }
    
    
    public void robotInit(){
        
        public DifferentialDrive m_robotDrive = new DifferentialDrive(leftMotor::set, rightMotor::set);
        public Joystick m_leftStick = new Joystick(0);
        public Joystick m_rightStick = new Joystick(1);
    }

    public void setSpeed(PWMVictorSPX motor, double speed){
        motor.set(speed);
    }

    public void setVoltage(PWMVictorSPX motor, double voltage){
        motor.setVoltage(voltage);
    }

    public void teleopPeriodic(){
        m_robotDrive.tankDrive(-m_leftStick.getY(), -m_rightStick.getY());
    }

    public void simulationPeriodic(){

    }

    public void drive(double left, double right){

    }
}
